name: versioning_test
description: An absolute bare-bones web app.
version: 1.0.0
# homepage: https://www.example.com
publish_to: none
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  package_a:
    path: ./package_a
    version: 1.0.1

dev_dependencies:
  build_runner: ^2.1.4
  build_web_compilers: ^3.2.1
  lints: ^2.0.0
