name: package_a
description: A starting point for Dart libraries or applications.
version: 1.0.1
# homepage: https://www.example.com
publish_to: none
environment:
  sdk: ">=2.17.0 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
